### PR TITLE
nimibook docs + 2 fixes + 1 feature (cfg) + 1 refactor

### LINKED ISSUE #10: example book should be nimibook documentation
right now the content of book is a minimal structure barely related to scinim/getting-started.
the book should instead document nimibook itself.

### PR DESCRIPTION
**Pull request by pietroppeter**
fix #10

- [X] (_fix_) removed `nimibook / prelude` (was broken); replaced with template `nbUseNimibook`
- [X] removed all previous content
- [X] expand README
- [X] new structure of documentation
- [X] (_refactor_) use template in `genbook` for book tasks (currently they are compile time switches. they should actually be available through a real CLI)
- [x] (_fix_) fix bug in `draft` (if in section it does not get indented)
- [x] (_feature_) add a way to configure stuff (book title and such), the idea is to create a `Book` object that will contain the `Toc` object and will have the fields needed to configure stuff. `toc.json` will become `book.json` and so forth...
- [x] docs:
  - [X] chapter index: uses README (in principle I could add stuff in index which is not in README and also add stuff in README which is not in index but I have not yet taken advantage of that)
  - [X] chapter content: brief description of the structure of the book page
  - [X] chapter tocdsl: brief explanation of TocDSL
  - [x] chapter configuration: todo, the feature is missing!
  - [X] chapter tasks: automatically generated from nimble

### CODE REVIEW

File: src/nimibook/defaults.nim [hunk 1]
```diff
@@ -31,7 +31,11 @@ proc useNimibook*(nbDoc: var NbDoc) =
   nbDoc.context["git_repository_url"] = "https://github.com/pietroppeter/nimibook"
   nbDoc.context["git_repository_icon"] = "fa-github"
 
-  var toc = load("../book/toc.json")
+  let tocPath = "../book/toc.json"
+  if not tocPath.fileExists:
+    withDir("..".AbsoluteDir): # todo: add a withDir for RelativeDir in nimib /paths
```
Comment (Clonkk) [inline src/nimibook/defaults.nim:36]: "..".AbsoluteDir 

Isn't ".." a relative dir and not an absolute dir ?

Could that be replaced by ``getProjectPath.parentDir()`` (or maybe ``currentSourcePath.parentDir()``) or will that pose problem when distributing the binary ?

Comment (pietroppeter) [reply src/nimibook/defaults.nim:36]: yes, it is, see the comment. I like to use `withDir` which I added in nimib /paths; it came from nimscript and was added in fusion which I copied and pasted into nimib (since I was not sure how to put fusion requirements in nimble file). I want to add also a `withDir` with relative directory, but until now it is not there, so now it looks bad (at least it is good that you were able to notice it).

Regarding the other proposals, the rationale is that, nimib will currently use as homeDir `docs` and it would by default change currentDir to homeDir so a `..`.RelativeDir should always work with thefolder structure we plan `nimibook` to have. For your other suggestions maybe `getProjectPath` could work (does it get the dir of nimble file?), `currentSourcePath` probably not (since source could be in subfolders of `book`).

Anyway I will need to revise how paths are handled in nimib, since nimibook has challenged the choices I made, so the idea is: 1) for now have workarounds in nimibook; 2) understand a better design and implement in nimib; 3) update nimibook with the improved design from nimib

**Comment by pietroppeter** [comment]
ok PR is ready for review. I will leave it open for a bit if anyone wants to give an additional look, but I plan to merge tomorrow not after the publication of "This Month With Nim".

**Comment by HugoGranstrom** [comment]
I skimmed through the code and didn't find anything obviously wrong but I'm not as familiar as @Clonkk with the codebase. I've checked that it compiles on my machine and produces reasonable outputs. Thought at first that the code formatting was off but I then noticed you inlined some code in the nbText.

File: book/configuration.nim [hunk 2]
```diff
@@ -0,0 +1,54 @@
+import nimib, nimibook
+import std / [os, strutils, strscans, strformat]
+
+nbInit
+nbUseNimibook
+
+# the following is very dependent on how source is written
+proc readBookConfigFields: seq[string] =
+  # current folder is docs
+  let src = "../src/nimibook/types.nim"
```
Comment (Clonkk) [inline book/configuration.nim:10]: Unless I misunderstood something, why does the book rely upon parsing a file in ``src`` ?

I think we should keep ``book`` and ``src`` separate as much as possible.

Comment (Clonkk) [reply book/configuration.nim:10]: Also relative path based on "../" will break with Nimble; but that may be something to fix later on

File: book/index.nim [hunk 3]
```diff
@@ -1,10 +1,13 @@
...
+  for line in filename.lines:
+    if line.startsWith(text):
+      return result
+    result &= line & '\n'
 
-Instead I will just post some nim code:
-"""
-nbCode:
-  echo "hello mdbook!"
+nbText: "../README.md".readFileUntil("<!--SKIP")
```
Comment (Clonkk) [inline book/index.nim:12]: Is it a good idea to have ``book`` be dependent on content outside its own folder ?

File: src/nimibook/books.nim [hunk 4]
```diff
@@ -0,0 +1,68 @@
+import std / os
+import nimibook /  [types, entries]
+import jsony
+
+# fix for jsony: quote in string. https://github.com/treeform/jsony/issues/14
+proc dumpHook*(s: var string, v: string) =
+  when nimvm:
+    s.add '"'
+    for c in v:
+      case c:
```
Comment (Clonkk) [inline src/nimibook/books.nim:10]: Can this be simplified with the use of : 

* [addEscaped](https://nim-lang.github.io/Nim/system.html#addEscapedChar%2Cstring%2Cchar)
* [addQuoted](https://nim-lang.github.io/Nim/system.html#addQuoted%2Cstring%2CT)
* [escape](https://nim-lang.github.io/Nim/strutils.html#escape%2Cstring%2Cstring%2Cstring) / unescape

I didn't analyzed it in details, but it seems like we could simplify it ?

File: src/nimibook/books.nim [hunk 5]
```diff
@@ -0,0 +1,68 @@
...
+    template add(ss: ptr UncheckedArray[char], c1, c2: char) =
+      ss[at] = c1
+      inc at
+      ss[at] = c2
+      inc at
+
+    ss.add '"'
+    for c in v:
+      case c:
+      of '\\': ss.add '\\', '\\'
```
Comment (Clonkk) [inline src/nimibook/books.nim:41]: This should be a function if it's used more than once. DRY.

**Review by Clonkk — COMMENTED** [review]
I added my review. It's mostly some small interrogation or minor stuff that could be fixed in later PRs. 

In a nutshell : 
* Should ``book`` be dependent upon stuff outside of itself ? 
I understand the appeal to auto-document, but I think it would be better to do so by using ``import nimibook`` as a library instead of relying on relative ``../``


The changes are overall very good otherwise.

File: book/configuration.nim (hunk 2 above)
Comment (HugoGranstrom) [reply book/configuration.nim:10]: I was also confused about the src/book thing until I realized the file wasn't some kind of configuration file butit rather just one of the pages in the book which did some parsing of the doc-comments in src. 🤦‍♂️

Comment (pietroppeter) [reply book/configuration.nim:10]: This `book` being the documentation of what happens in `src`, I think it is fair to make `book` depend on `src` to avoid repeating stuff and keep documentation up to date. The moment you add a new field to `Book` object implementing another feature you will get the corresponding documentation. For sure we should avoid having `src` depend on `book` folder. `book` folder should be forgotten when installed by nimble so the relative paths there should not matter.

Regarding the implementation, it is indeed a bit hacky (main drawback being that how you add and document fields in `Book` object impacts the documentation), but I think it is also rather straightforward. Other options I had in mind for implementation of this autodocumenting configurations were:

1. `nim jsondoc ...` and parse json file (will also depend directly on src)
2. use `macros.getImpl` and parse AST (this depends only on import nimibook, but since we will not have nimibook as a dependency here, it will still ultimately depend on src)

The only option to not depend on `src` folder is to duplicate documentation in code and `book` and I would prefer to avoid this unless there are specific issues.

File: book/index.nim (hunk 3 above)
Comment (pietroppeter) [reply book/index.nim:12]: see remarks above, but also reading README I think is rather harmless. I was planning to have distinct contents only for README.md and index.nim but in the end I did not use that feature.

File: src/nimibook/books.nim (hunk 4 above)
Comment (pietroppeter) [reply src/nimibook/books.nim:10]: this and the following I think it should be better addressed in [this PR to jsony](https://github.com/treeform/jsony/pull/15). I ran into the issue while dumping `Book` object, found the fix and directly applied it. When jsony merges the fix we should remove this and update jsony requirement.

**Comment by pietroppeter** [comment]
Thanks all for the reviews.

> In a nutshell :
> 
> * Should `book` be dependent upon stuff outside of itself ?
>   I understand the appeal to auto-document, but I think it would be better to do so by using `import nimibook` as a library instead of relying on relative `../`. CI based on relative folder can also be deceiving.

my thoughts on this (as reported below also in a comment):

This book being the documentation of what happens in `src`, I think it is fair to make `book` depend on `src` to avoid repeating stuff and keep documentation up to date. The moment you add a new field to `Book` object implementing another feature you will get the corresponding documentation. For sure we should avoid having `src` depend on `book` folder. `book` folder should be forgotten when installed by nimble so the relative paths in there should not matter.

I do not see any other option to not depend on `src` folder other than duplicating documentation in code and book and I would prefer to avoid this unless there are specific issues.

I will go ahead and merge, feel free to open an issue and argue more on this if my arguments were not convincing (I might change my mind in the end...) :)

File: book/configuration.nim (hunk 2 above)
Comment (Clonkk) [reply book/configuration.nim:10]: Options 2 was what I had in mind to do this but I understand your reasoning. 

I think in the long run we need a macros so that we can extract information from the AST for using Nimibook as a API documentation generator (replacement of Nim doc).

But it's a rather complex feature so maybe I think we should merge this first and improve upon it later.

File: book/index.nim (hunk 3 above)
Comment (Clonkk) [reply book/index.nim:12]: Yeah for a static Readme file it's fair game.
